name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name : Windows x64
            os: windows-2022
            runtime: win-x64
          - name : Linux
            os: ubuntu-latest
            runtime: linux-x64

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get git tag
      uses: little-core-labs/get-git-tag@v3.0.2
      id: tag_name
      with:
        tagRegex: "v(.*)"
        tagRegexGroup: 1

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore

    - name: Create artifact
      run: |
        dotnet publish -c ReleaseAOT --runtime ${{ matrix.runtime }} Launcher --output Publish/ /p:AssemblyVersion=${{ steps.tag_name.outputs.tag || '0.0.0' }}

    # - name: Compress Artifact
    #   if: ${{ startsWith(matrix.runtime, 'win-') }}
    #   run: |
    #     Compress-Archive Publish Seed-win64.zip

    - name: Create AppImage
      if: ${{ startsWith(matrix.runtime, 'linux-') }}
      run: |
        sudo apt-get install desktop-file-utils
        wget https://github.com/AppImage/appimagetool/releases/download/1.9.0/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        mkdir -p AppDir/usr/bin
        cp Publish/* AppDir/usr/bin
        ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir Seed.AppImage

    - name: Install Inno Setup 6.4.3 and Add to PATH
      if: ${{ startsWith(matrix.runtime, 'win-') }}
      run: |
        $installer = "is.exe"
        Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.4.3.exe" -OutFile $installer
        Start-Process -Wait -FilePath ".\$installer" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-"
        echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Create Installer
      if: ${{ startsWith(matrix.runtime, 'win-') }}
      run:
        ISCC.exe /dversion=${{ steps.tag_name.outputs.tag || '0.0.0' }} InnoSetup\Setup.iss

    - name: Upload artifact
      if: ${{ startsWith(matrix.runtime, 'linux-') }}
      uses: actions/upload-artifact@v4
      with:
        name: Seed.${{ matrix.runtime }}
        path: Seed.AppImage

    - name: Upload artifact
      if: ${{ startsWith(matrix.runtime, 'win-') }}
      uses: actions/upload-artifact@v4
      with:
        name: Seed.${{ matrix.runtime }}
        path: InnoSetup/Output/Seed_v${{ steps.tag_name.outputs.tag || '0.0.0' }}.exe