name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore

    - name: Create Linux artifact
      run: dotnet publish --configuration ${{ matrix.configuration }} --runtime linux-x64 --self-contained false -p:PublishReadyToRun=false Seed --output Publish/Linux -p:DebugType=None -p:DebugSymbols=false

    - name: Zip Linux artifact
      run: Compress-Archive -Path Publish/Linux -DestinationPath Publish/Linux.zip
      
    - name: Create Windows artifact
      run: dotnet publish --configuration ${{ matrix.configuration }} --runtime win-x64 --self-contained false -p:PublishReadyToRun=false Seed --output Publish/Windows -p:DebugType=None -p:DebugSymbols=false

    - name: Zip Windows artifact
      run: Compress-Archive -Path Publish/Windows -DestinationPath Publish/Windows.zip

    - name: Make Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Publish/Linux.zip
          Publish/Windows.zip
        generate_release_notes: true
        tag_name: ${{ github.ref }}
