name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name : Windows x64
            os: windows-2022
            runtime: win-x64
          - name : Linux
            os: ubuntu-latest
            runtime: linux-x64

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore

    - name: Create artifact
      run: dotnet publish -c ReleaseAOT --runtime ${{ matrix.runtime }} Launcher --output Publish/

    - name: Create AppImage
      if: ${{ startsWith(matrix.runtime, 'linux-') }}
      run: |
        sudo apt-get install desktop-file-utils
        wget https://github.com/AppImage/appimagetool/releases/download/1.9.0/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        mkdir -p AppDir/usr/bin
        cp Publish/* AppDir/usr/bin
        rm AppDir/usr/bin/Launcher.dbg
        ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir Seed.AppImage

    - name: Upload artifact
      if: ${{ startsWith(matrix.runtime, 'linux-') }}
      uses: actions/upload-artifact@v4
      with:
        name: Seed.${{ matrix.runtime }}
        path: Seed.AppImage

    - name: Upload artifact
      if: ${{ startsWith(matrix.runtime, 'win-') }}
      uses: actions/upload-artifact@v4
      with:
        name: Seed.${{ matrix.runtime }}
        path: Publish/*